import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Providers from "./_components/Providers";
import NavBar from "./_components/NavBar";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`absolute bg-[#191C21] w-full h-full ${font.className}`}>
          <NavBar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
